### ISSUE TITLE
Fails to build on Arch Linux

### ISSUE THREAD

**Issue by mikroskeem** [max-moser/network-manager-wireguard#14]
[Error log](https://paste.wut.ee/tumekikali.coffeescript)

If you need more information, let me know :smile:

**Comment by DDiPuma** [comment]
I have the same error.

For what it's worth, I had to manually add gettext as a dependency, so the PKGBUILD file is slightly incorrect, regardless of this error.

**Comment by Jupadr** [comment]
I have the same problem. I added gettext as a dependency to the PKGBUILD but it still won't compile with the same error message

**Comment by defkev** [comment]
Bug in libnm.

See https://cgit.freedesktop.org/NetworkManager/NetworkManager/commit/?id=0a3755c1799d3a4dc1875d4c59c7c568a64c8456

Either patch `libnm/nm-version.h` yourself (replace the second **comma** with a **dot**) or wait for it to hit upstream.

**Comment by Necklaces** [comment]
This can probably be closed, at least I'm able to build it on Arch. Then again, it's been almost two years.
