### ISSUE TITLE
Conversion to embeddable library

### ISSUE THREAD

**Issue by Emantor** [max-moser/network-manager-wireguard#2]
Hello,

I saw that you already integrated the embeddable library, did you start work on using it yet? I can't find a branch on this repository with work on that. I want to make sure we are not working in parallel on the same thing without knowing of the duplicate effort.

**Comment by max-moser** [comment]
Hey,

Just today I started writing the first few lines of code, but there's not too much effort in that yet.
If you want to work on that, I'll focus more on other parts for now

**Comment by Emantor** [comment]
I'm basically at the same step. Not sure how far I'll get over the weekend, I'll open a PR as soon as I get a basic working version. Thanks :+1:
