### ISSUE TITLE
Does not appear in Fedora 35

### ISSUE THREAD

**Issue by Vysp3r** [max-moser/network-manager-wireguard#52]
I've recently installed Fedora 35 and wanted to install this because for me this is a must, but I wasn't able to do. I've tried with these commands so far.

```
git clone https://github.com/max-moser/network-manager-wireguard.git
cd network-manager-wireguard/
./autogen.sh --without-libnm-glib
./configure --without-libnm-glib --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib/ --libexecdir=/usr/lib/NetworkManager --localstatedir=/var 
make
sudo make install
```

It compiles and seems to be installed when I check '/usr/lib/NetworkManager', but it does not show in the GUI. Do you have any idea why? I think it may be because the directories I use in the configuration are not good for fedora, but I don't know.

**Comment by nmaggioni** [comment]
Here's what worked for me, adapted from the [AUR PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=networkmanager-wireguard-git) and #57:

```bash
./autogen.sh --with-libnm-glib=no --disable-static --enable-more-warnings=no --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib/NetworkManager --localstatedir=/var
make
sudo make install
sudo sed -i 's|plugin=libnm-vpn-plugin-wireguard.so|plugin=/usr/lib64/NetworkManager/libnm-vpn-plugin-wireguard.so|g' /usr/lib/NetworkManager/VPN/nm-wireguard-service.name
```

Then restart NetworkManager and the Gnome shell or simply reboot.

**Comment by Vysp3r** [comment]
Thanks you, now it works!
